config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about' => 'pages#about'

  # Login page
  get '/login' => 'sessions#new', :as => 'login'

  # Sign Up
  post '/login' => 'sessions#create'

  # Logout
  delete '/logout' => 'sessions#destroy'

  get '/posts' => 'posts#show_all', :as => 'posts'


  post '/users/:user_id/posts/:post_id/comments/magictouch' => 'comments#create_magic_touch', :as => 'magic_touch'
  post '/users/:user_id/posts/:post_id/comments/mainstream' => 'comments#create_mainstream', :as => 'mainstream'
  post '/users/:user_id/posts/random' => 'posts#create_random_post', :as => 'random_post'
  # User routes
  resources :users do
    member do
      get :following, :followers
    end
    # Post routes
    resources :posts do
      # Comment routes
      resources :comments do
      end
    end
  end

  resources :relationships, :only => [ :create, :destroy ]

  end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id           :integer          not null, primary key
#  comment_post :text
#  post_id      :integer
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @post = Post.find_by( :id => params[ :post_id ] )
    @comments = @post.comments.order( created_at: :desc )
    @comment = Comment.new
    @templates = templates
  end

  def show
  end

  def create

    comment = Comment.new

    if params[ :file ].present?
      req = Cloudinary::Uploader.upload( params[ :file ] )
      comment.comment_post = req[ 'public_id' ]
    end

    comment.user_id = @current_user.id
    comment.post_id = params[ :post_id ]
    comment.save

    post = comment.post_id
    user = comment.user_id

    redirect_to( user_post_comments_path( :user_id => user, :post_id => post ) )

  end

  def create_magic_touch
    comment = Comment.new

    if params[ :file ].present?
      req = Cloudinary::Uploader.upload( params[ :file ] )

      img_with_text = Cloudinary::Uploader.text( params[ :top_text ],
                                                 :public_id => req[ 'public_id' ],
                                                 :font_family => "Roboto",
                                                 :font_size => 42,
                                                 :font_color => "black",
                                                 :font_weight => "bold" )

      comment.comment_post = img_with_text[ 'secure_url' ]
    end

    user = @current_user.id
    post = params[ :post_id ]

    comment.post_id = post
    comment.user_id = user

    if comment.save
      redirect_to( user_post_comments_path( :user_id => user, :post_id => post  ) )
    else
      render :index
    end
  end

  def create_mainstream

    top_text = params[ :top_text ]
    top_text = top_text.tr( " ", "-" )
    top_text = top_text.tr( "-", "--" )
    top_text = top_text.tr( "_", "__" )

    bottom_text = params[ :bottom_text ]
    bottom_text = bottom_text.tr( " ", "-" )
    bottom_text = bottom_text.tr( "-", "--" )
    bottom_text = bottom_text.tr( "_", "__" )

    template_id = params[ :template_id ]
    link = template_links[ template_id.to_i - 1 ]

    response = HTTParty.get( link + "/#{ top_text }/#{ bottom_text }" )

    img = response["direct"]["masked"]


    comment = Comment.new
    comment.comment_post = img
    comment.user_id = @current_user.id
    comment.post_id = params[ :post_id ]
    comment.save

    user = @current_user.id
    post = params[ :post_id ]

    redirect_to( user_post_comments_path( :user_id => user, :post_id => post ) )
  end

  # NO EDIT AND UPDATE SINCE EDITING NOT ALLOWED FOR COMMENTS

  def destroy
    comment = Comment.find_by( :id => params[ :id ] )
    comment.destroy
    redirect_to( user_post_comments_path( :user_id => params[ :user_id ], :post_id => params[ :post_id ] ) )
  end

  private
    def comment_params
      params.require( :comment ).permit( :comment_post, :user_id, :post_id )
    end

    def templates
      [
        [ "10 Guy", 1 ],
        [ "Afraid to Ask Andy", 2 ],
        [ "An Older Code Sir, But It Checks Out", 3 ],
        [ "Ancient Aliens Guy", 4 ],
        [ "Baby Insanity Wolf", 5 ],
        [ "Bad Luck Brian", 6 ],
        [ "But That's None of My Business", 7 ],
        [ "Butthurt Dweller", 8 ],
        [ "Captain Hindsight", 9 ],
        [ "Comic Book Guy", 10 ],
        [ "Condescending Wonka", 11 ],
        [ "Confession Bear", 12 ],
        [ "Conspiracy Keanu", 13 ],
        [ "Dating Site Murderer", 14 ],
        [ "At Least You Tried", 15 ],
        [ "Do It Live!", 16 ],
        [ "Do You Want Ants?", 17],
        [ "Doge", 18],
        [ "Drake Always On Beat", 19],
        [ "Ermahgerd", 20],
        [ "Facepalm", 21],
        [ "First World Problems", 22],
        [ "Forever Alone", 23],
        [ "Foul Bachelor Frog", 24],
        [ "Fuck Me, Right?", 25],
        [ "Futurama Fry", 26],
        [ "Good Guy Greg", 27],
        [ "Hipster Barista", 28],
        [ "I Can Has Cheezburger?", 29],
        [ "I Feel Like I'm Taking Crazy Pills", 30],
        [ "I Guarantee It", 31]
      ]
    end

    def template_links
      [
        "https://memegen.link/api/templates/tenguy",
        "https://memegen.link/api/templates/afraid",
        "https://memegen.link/api/templates/older",
        "https://memegen.link/api/templates/aag",
        "https://memegen.link/api/templates/biw",
        "https://memegen.link/api/templates/blb",
        "https://memegen.link/api/templates/kermit",
        "https://memegen.link/api/templates/bd",
        "https://memegen.link/api/templates/ch",
        "https://memegen.link/api/templates/cbg",
        "https://memegen.link/api/templates/wonka",
        "https://memegen.link/api/templates/cb",
        "https://memegen.link/api/templates/keanu",
        "https://memegen.link/api/templates/dsm",
        "https://memegen.link/api/templates/tried",
        "https://memegen.link/api/templates/live",
        "https://memegen.link/api/templates/ants",
        "https://memegen.link/api/templates/doge",
        "https://memegen.link/api/templates/alwaysonbeat",
        "https://memegen.link/api/templates/ermg",
        "https://memegen.link/api/templates/facepalm",
        "https://memegen.link/api/templates/fwp",
        "https://memegen.link/api/templates/fa",
        "https://memegen.link/api/templates/fbf",
        "https://memegen.link/api/templates/fmr",
        "https://memegen.link/api/templates/fry",
        "https://memegen.link/api/templates/ggg",
        "https://memegen.link/api/templates/hipster",
        "https://memegen.link/api/templates/icanhas",
        "https://memegen.link/api/templates/crazypills",
        "https://memegen.link/api/templates/mw",
      ]
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<div class="row">
  <div class="col s12 m8 offset-m2 l6 offset-l3">
    <div class="card">
      <div class="card-image">
        <%= image_tag @post.post_gif %>
      </div>
      <div class="card-content row valign-wrapper">
        <div class="col s2">
          <% if @post.user.profile_img.include?( 'http:' ) || @post.user.profile_img.include?( 'https:' ) %>
            <%= image_tag @post.user.profile_img, :alt => @post.user.name, :class => "circle responsive-img" %>
          <% else %>
            <%= cl_image_tag @post.user.profile_img, :alt => @post.user.name, :class => "circle responsive-img" %>
          <% end %>
        </div>
        <div class="col s10">
          <span class="card-title grey-text text-darken-4"><%= @post.caption %></span>
          <p>Posted <%= time_ago_in_words( @post.created_at ) %> ago</p>
        </div>
      </div>
      <div class="card-action right-align">
        <%= link_to( "I want to comment", "#modalcomment", :class => "modal-trigger waves-effect waves-light btn deep-purple lighten-2" ) %>
        <% if @current_user.id == @post.user.id %>
          <%= link_to( "Delete Post", user_post_path( :id => @post, :user_id => @post.user.id ), :method => "delete", :class => "modal-trigger waves-effect waves-light btn deep-purple lighten-2" ) %>
        <% end %>
      </div>

    </div>
  </div>
</div>


<% @comments.each do | comment | %>
  <% if @current_user.id == comment.user.id %>
    <div class="row">
      <div class="col s12 m8 offset-m2 l6 offset-l3">
          <div class="card">
            <div class="card-image">
              <% if comment.comment_post.include?( "http://" ) || comment.comment_post.include?( "https://" ) %>
                <%= image_tag( comment.comment_post ) %>
              <% else %>
                <%= cl_image_tag( comment.comment_post ) %>
              <% end %>
            </div>
            <div class="card-content row valign-wrapper">
              <div class="col s2">
                <% if comment.user.profile_img.include?( 'http:' ) || comment.user.profile_img.include?( 'https:' ) %>
                  <%= image_tag comment.user.profile_img, :alt => comment.user.name, :class => "circle responsive-img" %>
                <% else %>
                  <%= cl_image_tag comment.user.profile_img, :alt => comment.user.name, :class => "circle responsive-img" %>
                <% end %>
              </div>
              <div class="col s10">
                <span class="card-title grey-text text-darken-4">Commented by <%= comment.user.name %></span>
                <p>Commented <%= time_ago_in_words( comment.created_at ) %> ago</p>
              </div>
            </div>
            <div class="card-action right-align">
              <%= link_to( "Delete comment", user_post_comment_path( comment.post.user_id, comment.post_id, comment.id  ), :method => "delete", :class => "deep-purple lighten-2 btn" ) %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
    <div class="row">
      <div class="col s12 m8 offset-m2 l6 offset-l3">
          <div class="card">
            <div class="card-image">
              <% if comment.comment_post.include?( "http://" ) || comment.comment_post.include?( "https://" ) %>
                <%= image_tag( comment.comment_post ) %>
              <% else %>
                <%= cl_image_tag( comment.comment_post ) %>
              <% end %>
            </div>
            <div class="card-content row valign-wrapper">
              <div class="col s2">
                <% if comment.user.profile_img.include?( 'http:' ) || comment.user.profile_img.include?( 'https:' ) %>
                  <%= image_tag comment.user.profile_img, :alt => comment.user.name, :class => "circle responsive-img" %>
                <% else %>
                  <%= cl_image_tag comment.user.profile_img, :alt => comment.user.name, :class => "circle responsive-img" %>
                <% end %>
              </div>
              <div class="col s10">
                <span class="card-title grey-text text-darken-4">Commented by <%= comment.user.name %></span>
                <p>Commented <%= time_ago_in_words( comment.created_at ) %> ago</p>
              </div>
            </div>

          </div>
        </div>
      </div>
    <% end %>
<% end %>

  <!-- Modal Structure -->
  <div id="modalcomment" class="modal">
    <div class="modal-content">
      <h4 class="center-align">Comments</h4>
      <div class="row">
        <div class="col s12">
          <ul class="tabs tabs-fixed-width">
            <li class="tab col s3"><a class="active" href="#takedefault">Take As It Is</a></li>
            <li class="tab col s3"><a href="#mainstream">Mainstream</a></li>
          </ul>
        </div>
        <div id="takedefault" class="col s12">
          <%= form_for @comment, :url => user_post_comments_path( :user_id => @post.user.id, :post_id => @post ), :html => { :multipart => true } do | comment | %>
             <div>
               Image: <%= comment.cl_image_upload :comment_post, :placeholder => "Add comment...", :required => true %>
             </div>
             <div class="right-align">
               <%= comment.submit "Comment", :class => "modal-action modal-close waves-effect waves-green btn-flat" %>
             </div>
          <% end %>
        </div>
        <div id="mainstream" class="col s12">
          <%= form_tag mainstream_path( :user_id => @post.user.id, :post_id => @post ), :method => "post", :html => { :multipart => true } do %>
             <div>
               Top text: <%= text_field_tag :top_text %>
             </div>
             <div>
               Bottom text: <%= text_field_tag :bottom_text %>
             </div>
             <%= label_tag "Template" %>
             <div class="input-field col s12">
              <%= select_tag( :template_id, options_for_select( @templates ) )%>
             </div>
             <div class="right-align">
               <%= submit_tag "Comment", :class => "modal-action modal-close waves-effect waves-green btn-flat" %>
             </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
    </div>
  </div>
</div>