config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about' => 'pages#about'

  # Login page
  get '/login' => 'sessions#new', :as => 'login'

  # Sign Up
  post '/login' => 'sessions#create'

  # Logout
  delete '/logout' => 'sessions#destroy'

  get '/posts' => 'posts#show_all', :as => 'posts'


  post '/users/:user_id/posts/:post_id/comments/magictouch' => 'comments#create_magic_touch', :as => 'magic_touch'
  post '/users/:user_id/posts/:post_id/comments/mainstream' => 'comments#create_mainstream', :as => 'mainstream'
  post '/users/:user_id/posts/random' => 'posts#create_random_post', :as => 'random_post'
  # User routes
  resources :users do
    member do
      get :following, :followers
    end
    # Post routes
    resources :posts do
      # Comment routes
      resources :comments do
      end
    end
  end

  resources :relationships, :only => [ :create, :destroy ]

  end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :text
#  name            :text
#  email           :text
#  profile_img     :text
#  biography       :text
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :comments

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy

  has_many :follower, :through => :active_relationships, source: :followed
  has_many :followed, :through => :passive_relationships, source: :follower

  # Follow a user
  def follow( other_user )
    active_relationships.create( :followed_id => other_user.id )
  end

  # Unfollow a user
  def unfollow( other_user )
    binding.pry
    active_relationships.find_by( :followed_id => other_user.id ).destroy
  end

  def following?( other_user )
    followed.include?( other_user )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorise, :only => [ :edit, :update ]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by( :id => params[ :id ] )
  end

  def edit
    @user = @current_user
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new( user_params )
    if @user.save
      session[ :user_id ] = @user.id
      redirect_to( user_path( @user ) )
    else
      render :new
    end
  end

  def update

    user = @current_user

    if params[ :file ].present?
      req = Cloudinary::Uploader.upload( params[ :file ] )
      user.profile_img = req[ 'public_id' ]
    end

    user.assign_attributes( user_params )

    if user.save
      redirect_to user_path( user )
    else
      render :edit
    end
  end

  def destroy

    user = @current_user
    user.destroy
    session[ :user_id ] = nil

    redirect_to root_path
  end

  private
    def user_params
      params.require( :user ).permit( :name, :username, :email, :profile_img, :biography, :password, :password_confirmation )
    end

    def authorise
      if !@current_user.present?
        flash[ :error ] = "You will need to log in."
        #redirect_to
      end
    end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_follow.html.erb
<%= form_for @current_user.active_relationships.build do | f | %>
  <div><%= hidden_field_tag :followed_id, :value => @user.id %></div>
  <%= f.submit "Follow", :class => "waves-effect waves-light btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
  <% if @current_user.following?( @user ) %>
    <%= render "unfollow" %>
  <% else %>
    <%= render "follow" %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for( @user, :html => { :multipart => true } ) do | u | %>
   <p>Name: <%= u.text_field :name %></p>
   <p>Username: @<%= @user.username %></p>
   <p>Email: <%= u.email_field :email %></p>
   <p>Profile Image: <%= u.cl_image_upload :profile_img %></p>
   <p>Biography: <%= u.text_field :biography %></p>
   <%= u.submit %>
<% end %>

app/views/users/_new_user.html.erb
<%= form_for @user do | u | %>
   <p>Username: <%= u.text_field :username %></p>
   <p>Email: <%= u.email_field :email %></p>
   <p>Password: <%= u.password_field :password %></p>
   <p>Password confirmation: <%= u.password_field :password_confirmation %></p>
   <%= u.submit %>
<% end %>

app/views/users/_stats.html.erb
<div class="stats">
  <a href="<%= following_user_path( @user ) %>">
  <strong id="following" class="stat">
    <%= @user.followed.count %>
  </strong>
  following
  </a>
  <a href="<%= followers_user_path( @user ) %>">
  <strong id="followers" class="stat">
    <%= @user.follower.count %>
  </strong>
  followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for @current_user.active_relationships.find_by( :followed_id => @user.id ), :method => :delete do | f | %>
<%= f.submit "Unfollow", :class => "waves-effect waves-light btn" %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit Your Gifer</h2>

<%= render :partial => "form" %>

app/views/users/index.html.erb
<h2>User index</h2>

app/views/users/new.html.erb
<h2>Create gifer</h2>

<%= render :partial => "new_user" %>

app/views/users/show.html.erb
<h2 class="center-align">Gifer Profile</h2>

<div class="col s12 m8 offset-m2 l6 offset-l3">
  <div class="card-panel grey lighten-5 z-depth-1">
    <div class="row valign-wrapper">
      <div class="col s2">
        <% if @user.profile_img  %>
         <%= cl_image_tag @user.profile_img, :class => "circle responsive-img" %>
        <% else %>
          <p>Get your image up and running!</p>
        <% end %>
      </div>
      <div class="col s8">
        <p>Name: <%= @user.name %></p>
        <p>Username: @<%= @user.username %></p>
        <p>Email: <%= @user.email %></p>
        <p>Biography: <%= @user.biography %></p>
        <div>
          <%= link_to( "Edit profile", edit_user_path( @user ), :class => "btn deep-purple lighten-2" ) %>
          <%= link_to( "Delete this profile", user_path( @user ), :method => "delete", :class => "btn deep-purple lighten-2" ) %>
        </div>
      </div>
    </div>
  </div>
</div>