config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about' => 'pages#about'

  # Login page
  get '/login' => 'sessions#new', :as => 'login'

  # Sign Up
  post '/login' => 'sessions#create'

  # Logout
  delete '/logout' => 'sessions#destroy'

  get '/posts' => 'posts#show_all', :as => 'posts'


  post '/users/:user_id/posts/:post_id/comments/magictouch' => 'comments#create_magic_touch', :as => 'magic_touch'
  post '/users/:user_id/posts/:post_id/comments/mainstream' => 'comments#create_mainstream', :as => 'mainstream'
  post '/users/:user_id/posts/random' => 'posts#create_random_post', :as => 'random_post'
  # User routes
  resources :users do
    member do
      get :following, :followers
    end
    # Post routes
    resources :posts do
      # Comment routes
      resources :comments do
      end
    end
  end

  resources :relationships, :only => [ :create, :destroy ]

  end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  caption    :text
#  post_gif   :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find_by( :id => params[ :user_id ] )
    @posts = @user.posts.order( created_at: :desc )
    @post = Post.new
  end

  def show
    # When viewing post, it shall be in the show all comments view
  end

  def create
    post = Post.new

    if params[ :file ].present?
      req = Cloudinary::Uploader.upload( params[ :file ] )
      post.post_gif = req[ 'public_id' ]
    end

    post.caption = post_params[ :caption ]
    post.user_id = @current_user.id
    post.save

    redirect_to( posts_path )
  end

  def create_random_post

     userid = params[ :user_id ]

     link = "http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC"
     req = HTTParty.get( link )

     giphy = req[ "data" ][ "image_original_url" ]

     quotelink = "http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en"
     req_quote = HTTParty.get( quotelink )
     quoteCaption = req_quote[ "quoteText" ]

     post = Post.new
     post.user_id = userid
     post.post_gif = giphy
     post.caption = quoteCaption
     post.save

     redirect_to( posts_path )
  end

  def edit
    @post = Post.new
  end

  def update
    post = Post.find_by( :id => params[ :id ] )
    post.update( post_params )

    redirect_to( user_posts_path( post.user) )
  end

  def destroy
    post = Post.find_by( :id => params[ :id ] )
    post.destroy

    redirect_to( user_posts_path( @current_user ) )
  end

  def show_all
    @posts = Post.order( created_at: :desc )
    @post = Post.new
  end

  private
    def post_params
      params.require( :post ).permit( :post_gif, :caption, :user_id )
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div class="col s12 m8 offset-m2 l6 offset-l3">
  <div class="card-panel">
    <div class="row valign-wrapper">
      <div class="col s2">
        <%= cl_image_tag @user.profile_img, :alt => @user.name, :class => "circle responsive-img" %>
      </div>
      <div class="col s8">
        <span class="profile-username-font"><%= @user.username %></span>
        <br />
        <span class="profile-name-font"><%= @user.name %></span>
        <%= @user.biography %>
        <div><span id="posts"><%= @user.posts.count %> posts</span></div>
        <div>
        </div>
      </div>
    </div>
  </div>
</div>
<br/>


<% @posts.each do | post | %>
  <div class="row">
    <div class="col s12 m8 offset-m2 l6 offset-l3">
      <div class="card hoverable">
        <div class="card-image">
          <%= link_to( cl_image_tag( post.post_gif ), user_post_comments_path( :user_id => post.user.id, :post_id => post.id ) )%>
        </div>
        <div class="card-content">
          <span class="card-title grey-text text-darken-4"><%= post.caption %></span>
          <p>Posted <%= time_ago_in_words( post.created_at ) %> ago</p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/show_all.html.erb
<div class="row">
  <ul class="collapsible col s12 m8 offset-m2 l6 offset-l3" data-collapsible="accordion">
    <li>
      <div class="collapsible-header center-align">Gif-load</div>
      <div class="collapsible-body">
        <div class="row">
          <div class="col s12">
            <ul class="tabs tabs-fixed-width">
              <li class="tab col s3"><a class="" href="#gifit">I gif it</a></li>
              <li class="tab col s3"><a href="#randomgif">Random Shit</a></li>
            </ul>
          </div>
          <div id="gifit" class="col s12">
            <%= form_for @post, :url => user_posts_path( :user_id => @current_user ), :html => { :multipart => true } do | f | %>
              <div><%= f.text_field :caption, :placeholder => "Caption..." %></div>
              <div><%= f.cl_image_upload :post_gif %></div>
              <div class="right-align"><%= f.submit "Gif it!", :class => "deep-purple lighten-2 btn" %></div>
            <% end %>
          </div>
          <div id="randomgif" class="col s12">
            <br />
            <%= form_for @post, :url => random_post_path( :user_id => @current_user ), :html => { :multipart => true } do | f | %>
              <div class="center-align"><%= f.submit "I feel random!", :class => "deep-purple lighten-2 btn" %></div>
            <% end %>
          </div>
        </div>
      </div>
    </li>
  </ul>
</div>

<br />

<% @posts.each do | post | %>
  <div class="row">
    <div class="col s12 m8 offset-m2 l6 offset-l3">
      <div class="card hoverable">
        <div class="card-image">
          <%= link_to( cl_image_tag( post.post_gif, :class => "activator" ), user_post_comments_path( :user_id => post.user.id, :post_id => post.id ) )%>
        </div>
        <div class="card-content row valign-wrapper">
          <div class="col s2">
            <% if post.user.profile_img.include?( 'http://' ) || post.user.profile_img.include?( 'https://' ) %>
              <%= link_to( image_tag( post.user.profile_img, :alt => post.user.name, :class => "circle responsive-img" ), user_posts_path( :user_id => post.user.id ) ) %>
            <% else %>
              <%= link_to( cl_image_tag( post.user.profile_img, :alt => post.user.name, :class => "circle responsive-img" ), user_posts_path( :user_id => post.user.id ) ) %>
            <% end %>
          </div>
          <div class="col s10">
            <span class="card-title grey-text text-darken-4"><%= post.caption %></span>
            <p>Posted <%= time_ago_in_words( post.created_at ) %> ago</p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>