config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about' => 'pages#about'

  # Login page
  get '/login' => 'sessions#new', :as => 'login'

  # Sign Up
  post '/login' => 'sessions#create'

  # Logout
  delete '/logout' => 'sessions#destroy'

  get '/posts' => 'posts#show_all', :as => 'posts'


  post '/users/:user_id/posts/:post_id/comments/magictouch' => 'comments#create_magic_touch', :as => 'magic_touch'
  post '/users/:user_id/posts/:post_id/comments/mainstream' => 'comments#create_mainstream', :as => 'mainstream'
  post '/users/:user_id/posts/random' => 'posts#create_random_post', :as => 'random_post'
  # User routes
  resources :users do
    member do
      get :following, :followers
    end
    # Post routes
    resources :posts do
      # Comment routes
      resources :comments do
      end
    end
  end

  resources :relationships, :only => [ :create, :destroy ]

  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gif.gram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= cloudinary_js_config %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>

</head>
<body>

  <nav>
    <div class="nav-wrapper row deep-purple lighten-2">
      <% if @current_user.present? %>
        <%= link_to( "GifGram", posts_path, :class => "brand-logo col s4" ) %>
      <% else %>
        <%= link_to( "GifGram", root_path, :class => "brand-logo col s4" ) %>
      <% end %>
      <ul id="nav-mobile" class="right high-on-med-and-down">
        <% if @current_user.present? %>
          <li><%= link_to( "Gif-load", posts_path ) %></li>
          <li><%= link_to( "Gif-me", user_posts_path( @current_user ) ) %></li>
          <li><%= link_to( "Edit profile", user_path( @current_user ) ) %></li>
          <li><%= link_to( "Logout @#{ @current_user.username }", logout_path, :method => :delete ) %></li>
        <% else %>
          <li><%= link_to( "Home", root_path ) %></li>
          <li><%= link_to( "Sign In", login_path ) %></li>
          <li><%= link_to( "Sign Up", new_user_path ) %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <br />

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>